// 1
CREATE USER ISHRAK IDENTIFIED BY dragonsword05;
GRANT ALL PRIVILEGES TO ISHRAK;
CREATE TABLESPACE myspace datafile 'G:\Academic Study\Labs\5th Semester\RDBMS\Lab 3\myspace.dbf' SIZE 50M
extent management local autoallocate;
CREATE TABLESPACE myspace2 datafile 'G:\Academic Study\Labs\5th Semester\RDBMS\Lab 3\myspace2.dbf' SIZE 50M
extent management local autoallocate;
ALTER USER ISHRAK default tablespace myspace;
CREATE TABLE T1 (
    ID NUMBER,
    NAME VARCHAR2(20),
    CONSTRAINT PK_T1_ID PRIMARY KEY(ID)
);
CREATE TABLE T2 (
    ID NUMBER,
    NAME VARCHAR2(20),
    CONSTRAINT PK_T2_ID PRIMARY KEY(ID)
);
CREATE TABLE T3 (
    ID NUMBER,
    NAME VARCHAR2(20),
    CONSTRAINT PK_T3_ID PRIMARY KEY(ID)
);
CREATE TABLE T4 (
    ID NUMBER,
    NAME VARCHAR2(20),
    CONSTRAINT PK_T4_ID PRIMARY KEY(ID)
);
ALTER TABLE T1 move TABLESPACE myspace;
ALTER TABLE T2 move TABLESPACE myspace;
ALTER TABLE T3 move TABLESPACE myspace;
ALTER TABLE T4 move TABLESPACE myspace2;

// 2
CONN ISHRAK/dragonsword05

CREATE TABLE COURSES (
    ID NUMBER,
    NAME VARCHAR2(20),
    TEACHER VARCHAR2(20),
    CONSTRAINT PK_C_ID PRIMARY KEY (ID)
);

CREATE TABLE STUDENT (
    ID NUMBER,
    NAME VARCHAR2(20),
    COURSEID NUMBER,
    CONSTRAINT PK_S_ID PRIMARY KEY (ID),
    CONSTRAINT FK_SC_ID FOREIGN KEY (COURSEID) REFERENCES COURSES
);

INSERT INTO COURSES VALUES (101, 'RDBMS', 'ARMK');
INSERT INTO COURSES VALUES (102, 'Computer Networks', 'Sakhawat');
INSERT INTO COURSES VALUES (103, 'Algorithms', 'KH');
INSERT INTO COURSES VALUES (104, 'Probability', 'MMA');
INSERT INTO COURSES VALUES (105, 'OOP', 'Tariq');

INSERT INTO STUDENT VALUES (1, 'Ishfar', 101);
INSERT INTO STUDENT VALUES (2, 'Ishrak', 102);
INSERT INTO STUDENT VALUES (3, 'Nahid', 105);
INSERT INTO STUDENT VALUES (4, 'Lami', 102);
INSERT INTO STUDENT VALUES (5, 'Ovi', 101);
INSERT INTO STUDENT VALUES (6, 'Abir', 103);
insert into STUDENT VALUES (7, 'Ahbab', NULL);
insert into STUDENT VALUES (8, 'Sakif', NULL);

SELECT * FROM STUDENT
WHERE COURSEID IN (SELECT ID FROM COURSES WHERE ID < 103);

SELECT * FROM (SELECT * FROM STUDENT WHERE NAME LIKE '_sh%')
WHERE COURSEID >= 101;

// 3
SELECT S.NAME, C.NAME, C.TEACHER FROM STUDENT S LEFT JOIN COURSES C 
ON S.COURSEID = C.ID;
SELECT S.NAME, C.NAME, C.TEACHER FROM STUDENT S RIGHT JOIN COURSES C 
ON S.COURSEID = C.ID;