-- SET: MEDINA
-- TRY TO OPEN THE FILE USING ANY TEXT EDITOR LIKE NOTEPAD++ OR SUBLINE SO THAT THE CODE IS HIGHLIGHTED PROPERLY!

__\ 1 /__

-- i'M WRITING THE DDL_ TRY TO FIND OUT THE ERD FROM THIS.

--We need to register the customers at first.
CREATE TABLE CUSTOMER(
	ID NUMBER PRIMARY KEY,
	USERNAME VARCHAR2(30) UNIQUE,
	NAME VARCHAR2(30) NOT NULL,
	ADDRESS VARCHAR2(100),
	MOBILE_NUMBER NUMBER(11,0) NOT NULL,
	GENDER VARCHAR2(10),
	DOB DATE
);
-- THEN LET'S SAVE THE BRANCH INFO
CREATE TABLE BRANCH(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(30) NOT NULL,
	ESTD NUMBER(4),
	TOTAL_CAPACITY NUMBER
);
-- EACH BRANCH DOESN'T HAVE THE SAME SCHEDULE. THE SCHEDULE MAY VARY BASED ON DATE AND TIME. SO WE'LL maintain a schedule table. Each branch will have a schedule for each day on which it will be kept open (this was not mentioned in the questions, so multiple solutions possibel)

CREATE TABLE SCHEDULE(
	BRANCH_ID NUMBER,
	OPEN DATE,
	CLOSE DATE,
	DAY VARCHAR2(10),
	CHECK (DAY IN('SATURDAY','SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY')),
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(ID)
);

-- Before creating the menu, we need the foods to be entered into our system.
-- WE NEED TO CREATE A SEQUENCE FOR THE FOOD ID AS IT IS AUTO-GENERATED.
CREATE SEQUENCE FOOD_ID 
MINVALUE 1
START WITH 100
INCREMENT BY 1
CACHE 10;

CREATE TABLE FOODS(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(40),
	INGREDIENT VARCHAR2(100),
	FOOD_VALUE VARCHAR2(100),
	type VARCHAR2(20),
	CHECK (TYPE IN ('BREAKFAST','LUNCH','APPETIZER','DINNER'))
);

-- NOW IT'S time to create the menu. but the problem is the menu is not the same for all branches. So we need to save the branch id, food id, price in the menu. I've put a entry number for each menu entry so that the customers can order easily.

CREATE TABLE MENU(
	SERIAL_NUMBER NUMBER PRIMARY KEY,
	BRANCH_ID NUMBER,
	FOOD_iD NUMBER,
	PRICE NUMBER,
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(ID),
	FOREIGN KEY(FOOD_iD) REFERENCES FOODS(ID)
);

-- As the menu is now ready, let's take the order!

CREATE TABLE ORDERS(
	ORDER_NO NUMBER PRIMARY KEY,
	CUSTOMER_ID NUMBER,
	MENU_SERIAL NUMBER,
	DAY DATE,
	DESTINATION VARCHAR2(30),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
	FOREIGN KEY (MENU_SERIAL) REFERENCES MENU(SERIAL_NUMBER)
);

-- FINALLY COME THE FEEDBACK SECTION

CREATE TABLE FEEDBACK(
	CUSTOMER_ID NUMBER,
	MESSAGE VARCHAR2(255),
	FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);





___\ 2 /___



CREATE TABLE EMP(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(30),
	SALARY NUMBER	
);

INSERT INTO EMP VALUES(1,'SABBIR',12345);

--CREATING THE PROCEDURE

CREATE OR REPLACE PROCEDURE BONUS(T_ID IN NUMBER, MESSAGE OUT VARCHAR) AS

T_SALARY NUMBER;
T_NAME VARCHAR2(30);
BEGIN
	SELECT NAME, SALARY INTO T_NAME, T_SALARY
	FROM EMP
	WHERE ID=T_ID;

	IF(T_SALARY>50000) THEN MESSAGE:='Congratulations '||T_NAME||', your bonus is ' ||T_SALARY*0.3||' taka!';
	ELSIF(T_SALARY>30000) THEN MESSAGE:='Congratulations '||T_NAME||', your bonus is ' ||T_SALARY*0.25||' taka!';
	ELSE MESSAGE:='Congratulations '||T_NAME||', your bonus is ' ||T_SALARY*0.2||' taka!';
	END IF;


END BONUS;
/


--CALLING THE PROCEDURE
DECLARE
MESSAGE VARCHAR2(100);
BEGIN
	BONUS(1,MESSAGE);
	DBMS_OUTPUT.PUT_LINE(MESSAGE);
END;
/

SET SERVEROUT ON
/
Congratulations SABBIR, your bonus is 2469 taka!


-- if you face the problem "Warning: Procedure created with compilation errors."_ then type "show error" to find out the errors!


___\ 3 /___

	(A)
SELECT *
FROM PRODUCTS P, MANUFACTURER M
WHERE P.NAME LIKE 'M___%' AND P.MID=M.ID;

	(B)

SELECT PRICE
FROM(
	SELECT DISTINCT PRICE
	FROM PRODUCTS
	ORDER BY PRICE DESC
	)
WHERE ROWNUM<=3;

-- in the above problem, we first take the distinct ones. So even if a particular salary is entered many times in the table, it will be considered once. 

	(C)

SELECT P.NAME,M.NAME
FROM PRODUCTS P, MANUFACTURER M
WHERE P.PRICE IN(
				SELECT PRICE
				FROM(
					SELECT ROWNUM AS RN,PRICE
					FROM(
						SELECT DISTINCT PRICE
						FROM PRODUCTS
						ORDER BY PRICE DESC
						)
					)
				WHERE RN=4
				) AND P.MID=M.ID;

-- HERE first I sorted the table basaed on distinct price
--		then assigning rownum so that it can be directly accessed
--		then accessing the 4th highest one

	(D)

CREATE OR REPLACE VIEW MEDINA_3D AS
SELECT P.NAME, M.NAME AS MANUFACTURER, PRICE
FROM PRODUCTS P, MANUFACTURER M
WHERE M.ID=P.MID;

SELECT * FROM MEDINA_3D;

-- either the product name or the manufacturer name needs to be renamed for avoiding conflict

	(E)
SELECT MANUFACTURER, COUNT(NAME)
FROM MEDINA_3D
GROUP BY MANUFACTURER;

--	result should be the following one:

	MANUFACTURER         COUNT(NAME)
	-------------------- -----------
	WALTON                         3
	UNILIVER                       2
	XIAOMI                         3
	PRAN                           2


	(F)

-- COMPLEX ONE
-- LETS SOLVE IT STEP BY STEP
STEP 1: FINDING THE AVERAGE PRICE PER MANUFACTURER
	SELECT M.NAME, AVG(PRICE) AS A_P
	FROM PRODUCTS P, MANUFACTURER M
	WHERE P.MID=M.ID
	GROUP BY M.NAME;

	NAME                        A_P
	-------------------- ----------
	WALTON                     6600
	UNILIVER                    135
	XIAOMI                     6600
	PRAN                         20

STEP 2: SELECTING THE DISTINCT AVERAGE PRICES FROM HERE AND SORTING THEM. 

	SELECT DISTINCT A_P
	FROM(
		SELECT M.NAME, AVG(PRICE) AS A_P
		FROM PRODUCTS P, MANUFACTURER M
		WHERE P.MID=M.ID
		GROUP BY M.NAME
		)
	ORDER BY A_P DESC;

	       A_P
	----------
	      6600
	       135
	        20
STEP 3: FINDIN THE 2ND highest AVERAGE PRICE FROM HERE:

	SELECT A_P
	FROM(
		SELECT ROWNUM AS RN, A_P
		FROM(
			SELECT DISTINCT A_P
			FROM(
				SELECT M.NAME, AVG(PRICE) AS A_P
				FROM PRODUCTS P, MANUFACTURER M
				WHERE P.MID=M.ID
				GROUP BY M.NAME
				)
			ORDER BY A_P DESC
			)
		)
	WHERE RN=2;

       A_P
----------
       135

STEP 4: NOW WE HAVE THE 2ND highest AVERAGE PRICE. NEXT TASK IS TO FIND OUT THE NAME ASSOCIATED WITH THIS AVERAGE PRICE. WE CANT ACCESS IT FROM THE PRODUCTS TABLE AS THE COMPARISON have to be done with the average price. So in the from section, we have to form a table with the manufacturer names along with the average price and try to find match with 2nd highest average price from that inner table. 

	SELECT NAME 
	FROM(
		SELECT M.NAME, AVG(PRICE) AS A_P
		FROM PRODUCTS P, MANUFACTURER M
		WHERE P.MID=M.ID
		GROUP BY M.NAME
		)
	WHERE A_P=(	SELECT A_P
				FROM(
					SELECT ROWNUM AS RN, A_P
					FROM(
						SELECT DISTINCT A_P
						FROM(
							SELECT M.NAME, AVG(PRICE) AS A_P
							FROM PRODUCTS P, MANUFACTURER M
							WHERE P.MID=M.ID
							GROUP BY M.NAME
							)
						ORDER BY A_P DESC
						)
					)
				WHERE RN=2
	);


	NAME
	--------------------
	UNILIVER

	(G)

SELECT *
FROM PRODUCTS P, MANUFACTURER M
WHERE P.MID=M.ID AND (M.NAME='WALTON' AND CATEGORY='SMARTPHONE') OR (M.NAME='XIAOMI' AND CATEGORY='SMARTPHONE');

	(H)

SELECT NAME 
FROM PRODUCTS
WHERE PRICE = 	(
				SELECT MAX(PRICE)
				FROM PRODUCTS
				)
UNION
SELECT NAME 
FROM PRODUCTS
WHERE PRICE = 	(
				SELECT MIN(PRICE)
				FROM PRODUCTS
				);


NAME
--------------------
NOTE 4
POTATO CRACKERS



	___\ 4 /___

STEP 1: CREATING THE USERS

CREATE USER OWNER1 IDENTIFIED BY TEST123;
CREATE USER OWNER2 IDENTIFIED BY TEST123;

CREATE USER DEVELOPER IDENTIFIED BY TEST123;

CREATE USER EMP1 IDENTIFIED BY TEST123;
CREATE USER EMP2 IDENTIFIED BY TEST123;
CREATE USER EMP3 IDENTIFIED BY TEST123;
CREATE USER EMP4 IDENTIFIED BY TEST123;
CREATE USER EMP5 IDENTIFIED BY TEST123;

CREATE USER CUSTOMER1 IDENTIFIED BY TEST123;
CREATE USER CUSTOMER2 IDENTIFIED BY TEST123;
CREATE USER CUSTOMER3 IDENTIFIED BY TEST123;

STEP 2: GRANTING LOGIN PERMISSIONS

GRANT CONNECT, CREATE SESSION TO OWNER1;
GRANT CONNECT, CREATE SESSION TO OWNER2;

GRANT CONNECT, CREATE SESSION TO DEVELOPER;

GRANT CONNECT, CREATE SESSION TO EMP1;
GRANT CONNECT, CREATE SESSION TO EMP2;
GRANT CONNECT, CREATE SESSION TO EMP3;
GRANT CONNECT, CREATE SESSION TO EMP4;
GRANT CONNECT, CREATE SESSION TO EMP5;

GRANT CONNECT, CREATE SESSION TO CUSTOMER1;
GRANT CONNECT, CREATE SESSION TO CUSTOMER2;
GRANT CONNECT, CREATE SESSION TO CUSTOMER3;

STEP 3: CREATING THE ROLES

CREATE ROLE OWNER;
CREATE ROLE NORMAL_USER;
CREATE ROLE EMP;

STEP 4: GRANTING PERMISSIONS TO THE ROLES

GRANT SELECT ON SYSTEM.CUSTOMER TO EMP;

GRANT SELECT ON SYSTEM.CUSTOMER TO OWNER;
GRANT INSERT ON SYSTEM.CUSTOMER TO OWNER;
GRANT UPDATE ON SYSTEM.CUSTOMER TO OWNER;
GRANT DELETE ON SYSTEM.CUSTOMER TO OWNER;
GRANT SELECT ON SYSTEM.FOODS TO OWNER;
GRANT INSERT ON SYSTEM.FOODS TO OWNER;
GRANT UPDATE ON SYSTEM.FOODS TO OWNER;
GRANT DELETE ON SYSTEM.FOODS TO OWNER;
GRANT SELECT ON SYSTEM.BRANCH TO OWNER;
GRANT INSERT ON SYSTEM.BRANCH TO OWNER;
GRANT UPDATE ON SYSTEM.BRANCH TO OWNER;
GRANT DELETE ON SYSTEM.BRANCH TO OWNER;

GRANT SELECT ON SYSTEM.CUSTOMER TO EMP;
GRANT SELECT ON SYSTEM.FOODS TO EMP;
GRANT INSERT ON SYSTEM.CUSTOMER TO EMP;
GRANT INSERT ON SYSTEM.FOODS TO EMP;

STEP 5: GRANTING ROLES TO THE USERS

GRANT OWNER TO OWNER1;
GRANT OWNER TO OWNER2;
GRANT OWNER TO DEVELOPER;

GRANT EMP TO EMP1;
GRANT EMP TO EMP2;
GRANT EMP TO EMP3;
GRANT EMP TO EMP4;
GRANT EMP TO EMP5;

GRANT NORMAL_USER TO CUSTOMER1;
GRANT NORMAL_USER TO CUSTOMER2;
GRANT NORMAL_USER TO CUSTOMER3;


